INSERT INTO products (id, name, description, price) VALUES
                                                           ('P001', 'Cepillo de bambú', 'Cepillo dental ecológico de bambú biodegradable', 1990),
                                                           ('P002', 'Bolsas reutilizables', 'Set de bolsas reutilizables para compras', 4990),
                                                           ('P003', 'Botella de acero inoxidable', 'Botella térmica reutilizable, 500 ml', 12990),
                                                           ('P004', 'Shampoo sólido', 'Shampoo ecológico en barra sin plásticos', 5990),
                                                           ('P005', 'Desodorante natural', 'Desodorante sin aluminio, biodegradable', 6490),
                                                           ('P006', 'Pajillas de acero', 'Set de 4 pajillas de acero inoxidable con cepillo', 3990),
                                                           ('P007', 'Toallas de tela reutilizables', 'Set de toallas sanitarias de algodón orgánico', 12990),
                                                           ('P008', 'Detergente ecológico', 'Detergente concentrado biodegradable', 8490),
                                                           ('P009', 'Esponja vegetal', 'Esponja natural de luffa para limpieza', 2490),
                                                           ('P010', 'Jabón artesanal', 'Jabón natural sin químicos ni envase plástico', 2990),
                                                           ('P011', 'Compostera doméstica', 'Mini compostera para residuos orgánicos', 34990),
                                                           ('P012', 'Copa menstrual', 'Alternativa ecológica a toallas y tampones', 15990),
                                                           ('P013', 'Servilletas de tela', 'Pack de 6 servilletas reutilizables', 7990),
                                                           ('P014', 'Cepillo para verduras', 'Cepillo de madera con fibras naturales', 3490),
                                                           ('P015', 'Vasos de bambú', 'Set de 4 vasos biodegradables', 8990),
                                                           ('P016', 'Cera para envolver alimentos', 'Paños de algodón con cera de abeja', 11990),
                                                           ('P017', 'Café orgánico', 'Café molido certificado 100% orgánico', 7490),
                                                           ('P018', 'Aceite de coco natural', 'Aceite de coco virgen sin refinar', 5990),
                                                           ('P019', 'Papel reciclado', 'Bloc de notas hecho con papel reciclado', 1990),
                                                           ('P020', 'Tetera solar', 'Tetera portátil que calienta con energía solar', 49990);
